
async function name(){
    try{

    }catch (error){
        console.log(error);
    }
}